name: Integration testing

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "wheel>=0.36"
          pip install -r requirements.txt
          ./fritz develop

      - name: Build and spin up
        run: |
          cp kowalski/docker-compose.defaults.yaml kowalski/docker-compose.yaml
          ./fritz run --init --dev

      - name: Run integration tests
        run: |
          ./fritz test

      - name: Upload skyportal logs
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: logs
          path: skyportal/logs
